parameters:
  - name: azureServiceConnection
    type: string
    default: 'Workload-Federation-AIRS-Subscription'
  - name: location
    type: string
    default: 'australiaeast'
  - name: prefix
    type: string
    default: 'acaadodemo'
  - name: vmImageName
    type: string
    default: 'ubuntu-latest'

jobs:
  - job: InfraProvisionJob
    variables:
    - name: deploymentName
      value: 'infra-deployment'
    displayName: Infrastructure Provision job
    pool:
      vmImage: ${{ parameters.vmImageName }}
    steps:

    - checkout: self 

    - script: |
        az bicep build --file ./main.bicep
      name: LintBicepTemplate
      displayName: 'Lint Bicep Template'

    - task: AzureCLI@2
      name: 'ValidateInfrastructureTask'
      displayName: 'Validate Infrastructure Task'
      enabled: true
      continueOnError: false
      inputs:
        azureSubscription: ${{ parameters.azureServiceConnection }}
        scriptLocation: inlineScript
        scriptType: bash
        inlineScript: |
          az deployment sub validate \
            --name $(deploymentName) \
            --location ${{ parameters.location }} \
            --template-file ./main.bicep \
            --parameters location=${{ parameters.location }} prefix=${{ parameters.prefix }}

    - task: AzureCLI@2
      name: 'WhatifInfrastructureTask'
      displayName: 'Whatif Infrastructure Task'
      enabled: true
      continueOnError:  false
      inputs:
        azureSubscription: ${{ parameters.azureServiceConnection }}
        scriptLocation: inlineScript
        scriptType: pscore
        inlineScript: |
          $result=$(az deployment sub what-if `
            --name $(deploymentName) `
            --location ${{ parameters.location }} `
            --template-file ./main.bicep `
            --parameters location=${{ parameters.location }} prefix=${{ parameters.prefix }} `
            --no-pretty-print `
            --output json | ConvertFrom-Json)

          $result.changes.delta

    - task: AzureCLI@2
      name: 'ProvisionInfrastructureTask'
      displayName: 'Provision Infrastructure Task'
      enabled: true
      continueOnError: false
      inputs:
        azureSubscription: ${{ parameters.azureServiceConnection }}
        scriptLocation: inlineScript
        scriptType: bash
        inlineScript: |
          az deployment sub create \
            --name $(deploymentName) \
            --location ${{ parameters.location }} \
            --template-file ./main.bicep \
            --parameters location=${{ parameters.location }} prefix=${{ parameters.prefix }}
    
    - task: AzureCLI@2
      name: 'GetDeploymentOutputs'
      displayName: 'Get Deployment Outputs'
      enabled: true
      continueOnError: false
      inputs:
        azureSubscription: ${{ parameters.azureServiceConnection }}
        scriptLocation: inlineScript
        scriptType: bash
        inlineScript: |
          OUTPUT=$(az deployment sub show --name $(deploymentName) --query properties.outputs)

          acrName=$(echo $OUTPUT | jq -r '.acrName.value')
          resourceGroupName=$(echo $OUTPUT | jq -r '.resourceGroupName.value')
          acaEnvironmentName=$(echo $OUTPUT | jq -r '.acaEnvironmentName.value')
          acaEnvironmentId=$(echo $OUTPUT | jq -r '.acaEnvironmentId.value')
          umidId=$(echo $OUTPUT | jq -r '.umidId.value')

          echo "acrName: $acrName"
          echo "resourceGroupName: $resourceGroupName"
          echo "acaEnvironmentName: $acaEnvironmentName"
          echo "acaEnvironmentId: $acaEnvironmentId"
          echo "umidId: $umidId"

          echo "##vso[task.setvariable variable=resourceGroupName;isOutput=true;]$resourceGroupName"
          echo "##vso[task.setvariable variable=acrName;isOutput=true;]$acrName"
          echo "##vso[task.setvariable variable=acaEnvironmentName;isOutput=true;]$acaEnvironmentName"
          echo "##vso[task.setvariable variable=acaEnvironmentId;isOutput=true;]$acaEnvironmentId"
          echo "##vso[task.setvariable variable=umidId;isOutput=true;]$umidId"
