apiVersion: azure.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: provider-azure-config
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: flux-system
      name: azure-provider-creds
      key: credentials
