# This is a SecretProviderClass example using workload identity to access your key vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: akv-workload-identity-go-mtls # needs to be unique per namespace
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"          
    clientID: "<workloadIdentityClientId>" # Setting this to use workload identity
    keyvaultName: "<keyVaultName>"      # Set to the name of your key vault
    cloudName: "AzurePublicCloud"       # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: server-cert
          objectType: secret            # object types: secret, key, or cert
          objectVersion: ""             # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: ca-cert
          objectType: secret            # object types: secret, key, or cert
          objectVersion: ""             # [OPTIONAL] object versions, default to latest if empty
    tenantId: "<identityTenant>"       # The tenant ID of the key vault