apiVersion: v1
kind: Pod
metadata:
  name: webserver
  labels:
    name: webserver
spec:
  containers:
    - name: webserver
      image: nginx:alpine
      securityContext:
        readOnlyRootFilesystem: true
      ports:
        - containerPort: 80
      resources:
        limits:
          cpu: "0.5"
          memory: "512Mi"
        requests:
          cpu: "0.1"
          memory: "128Mi"
      volumeMounts:
        - mountPath: /var/run
          name: tmpfs
        - mountPath: /var/cache/nginx
          name: tmpfs-ram
  volumes:
    - name: tmpfs
      emptyDir: {}
    - name: tmpfs-ram
      emptyDir:
        medium: "Memory"
