apiVersion: v1
kind: ServiceAccount
metadata:
  name: podinfo
---
apiVersion: v1
kind: Service
metadata:
  name: podinfo
  labels:
    app: podinfo
    service: podinfo
spec:
  ports:
  - name: http
    port: 9898
  selector:
    app: podinfo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: podinfo
  template:
    metadata:
      labels:
        app: podinfo
    spec:
      serviceAccountName: podinfo
      nodeSelector:
        kubernetes.io/arch: amd64
        kubernetes.io/os: linux
      containers:
      - image: stefanprodan/podinfo
        imagePullPolicy: IfNotPresent
        name: podinfo
        ports:
        - containerPort: 9898